name: WattWise
options:
  bundleIdPrefix: com.example.wattwise
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  WattWise:
    type: application
    platform: iOS
    sources:
      - path: WattWise
    settings:
      base:
        INFOPLIST_FILE: WattWise/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.wattwise
        PRODUCT_NAME: WattWise
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: WattWiseWidgets
    entitlements:
      path: WattWise/WattWise.entitlements
      properties:
        com.apple.security.app-sandbox: true

  WattWiseWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: WattWiseWidgets
      - path: WattWise/Models/FamilyMember.swift
      - path: WattWise/Models/EnergyChallenge.swift
    settings:
      base:
        INFOPLIST_FILE: WattWiseWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.wattwise.widgets
        PRODUCT_NAME: WattWiseWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
