name: TenKiLog
options:
  bundleIdPrefix: com.example.tenkiLog
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  TenKiLog:
    type: application
    platform: iOS
    sources:
      - path: TenKiLog
    settings:
      base:
        INFOPLIST_FILE: TenKiLog/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.tenkiLog
        PRODUCT_NAME: TenKiLog
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: TenKiLogWidgets
    entitlements:
      path: TenKiLog/TenKiLog.entitlements
      properties:
        com.apple.security.app-sandbox: true

  TenKiLogWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: TenKiLogWidgets
    settings:
      base:
        INFOPLIST_FILE: TenKiLogWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.tenkiLog.widgets
        PRODUCT_NAME: TenKiLogWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
