name: BumpShare
options:
  bundleIdPrefix: com.example.bumpshare
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  BumpShare:
    type: application
    platform: iOS
    sources:
      - path: BumpShare
    settings:
      base:
        INFOPLIST_FILE: BumpShare/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.bumpshare
        PRODUCT_NAME: BumpShare
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: BumpShareWidgets
    entitlements:
      path: BumpShare/BumpShare.entitlements
      properties:
        com.apple.security.app-sandbox: true

  BumpShareWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: BumpShareWidgets
    settings:
      base:
        INFOPLIST_FILE: BumpShareWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.bumpshare.widgets
        PRODUCT_NAME: BumpShareWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
