name: CookSnap
options:
  bundleIdPrefix: com.example.cooksnap
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  CookSnap:
    type: application
    platform: iOS
    sources:
      - path: CookSnap
    settings:
      base:
        INFOPLIST_FILE: CookSnap/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.cooksnap
        PRODUCT_NAME: CookSnap
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    entitlements:
      path: CookSnap/CookSnap.entitlements
      properties:
        com.apple.security.app-sandbox: true
