name: FocusForge
options:
  bundleIdPrefix: com.example.focusforge
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  FocusForge:
    type: application
    platform: iOS
    sources:
      - path: FocusForge
    settings:
      base:
        INFOPLIST_FILE: FocusForge/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.focusforge
        PRODUCT_NAME: FocusForge
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SUPPORTS_LIVE_ACTIVITIES: YES
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: FocusForgeWidgets
    entitlements:
      path: FocusForge/FocusForge.entitlements
      properties:
        com.apple.security.app-sandbox: true

  FocusForgeWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: FocusForgeWidgets
      # 共有モデル（Widget からもアクセスが必要）
      - path: FocusForge/Models/PomodoroPhase.swift
      - path: FocusForge/Models/FocusForgeAlarmMetadata.swift
    settings:
      base:
        INFOPLIST_FILE: FocusForgeWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.focusforge.widgets
        PRODUCT_NAME: FocusForgeWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
