name: ChronoSense
options:
  bundleIdPrefix: com.example.chronosense
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  ChronoSense:
    type: application
    platform: iOS
    sources:
      - path: ChronoSense
    settings:
      base:
        INFOPLIST_FILE: ChronoSense/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.chronosense
        PRODUCT_NAME: ChronoSense
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: ChronoSenseWidgets
    entitlements:
      path: ChronoSense/ChronoSense.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.developer.sensorkit.reader.allow: true

  ChronoSenseWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: ChronoSenseWidgets
      - path: ChronoSense/Models/CircadianProfile.swift
      - path: ChronoSense/Models/SensorReading.swift
      - path: ChronoSense/Models/WeeklyRhythm.swift
    settings:
      base:
        INFOPLIST_FILE: ChronoSenseWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.chronosense.widgets
        PRODUCT_NAME: ChronoSenseWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
