name: MindMirror
options:
  bundleIdPrefix: com.example.mindmirror
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  MindMirror:
    type: application
    platform: iOS
    sources:
      - path: MindMirror
    settings:
      base:
        INFOPLIST_FILE: MindMirror/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.mindmirror
        PRODUCT_NAME: MindMirror
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: MindMirrorWidgets
    entitlements:
      path: MindMirror/MindMirror.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.developer.sensorkit.reader.allow: true

  MindMirrorWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: MindMirrorWidgets
      - path: MindMirror/Models/MentalHealthScore.swift
      - path: MindMirror/Models/BehaviorMetrics.swift
      - path: MindMirror/Models/DailyReport.swift
    settings:
      base:
        INFOPLIST_FILE: MindMirrorWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.mindmirror.widgets
        PRODUCT_NAME: MindMirrorWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
