name: MedicineGuard
options:
  bundleIdPrefix: com.example.medicineguard
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  MedicineGuard:
    type: application
    platform: iOS
    sources:
      - path: MedicineGuard
    settings:
      base:
        INFOPLIST_FILE: MedicineGuard/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.medicineguard
        PRODUCT_NAME: MedicineGuard
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SUPPORTS_LIVE_ACTIVITIES: YES
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: MedicineGuardWidgets
    entitlements:
      path: MedicineGuard/MedicineGuard.entitlements
      properties:
        com.apple.security.app-sandbox: true

  MedicineGuardWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: MedicineGuardWidgets
      # 共有モデル（Widget からもアクセスが必要）
      - path: MedicineGuard/Models/Medication.swift
      - path: MedicineGuard/Models/MedicationScheduleType.swift
      - path: MedicineGuard/Models/MedicineAlarmMetadata.swift
    settings:
      base:
        INFOPLIST_FILE: MedicineGuardWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.medicineguard.widgets
        PRODUCT_NAME: MedicineGuardWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
