name: LifeRewind
options:
  bundleIdPrefix: com.example.liferewind
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  LifeRewind:
    type: application
    platform: iOS
    sources:
      - path: LifeRewind
    settings:
      base:
        INFOPLIST_FILE: LifeRewind/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.liferewind
        PRODUCT_NAME: LifeRewind
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: LifeRewindWidgets
    entitlements:
      path: LifeRewind/LifeRewind.entitlements
      properties:
        com.apple.security.app-sandbox: true

  LifeRewindWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: LifeRewindWidgets
      - path: LifeRewind/Models/LifeEvent.swift
      - path: LifeRewind/Models/LifeStats.swift
    settings:
      base:
        INFOPLIST_FILE: LifeRewindWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.liferewind.widgets
        PRODUCT_NAME: LifeRewindWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
