name: GridPulse
options:
  bundleIdPrefix: com.example.gridpulse
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  GridPulse:
    type: application
    platform: iOS
    sources:
      - path: GridPulse
    settings:
      base:
        INFOPLIST_FILE: GridPulse/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.gridpulse
        PRODUCT_NAME: GridPulse
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: GridPulseWidgets
    entitlements:
      path: GridPulse/GridPulse.entitlements
      properties:
        com.apple.security.app-sandbox: true

  GridPulseWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: GridPulseWidgets
      - path: GridPulse/Models/GridState.swift
      - path: GridPulse/Models/EnergyArt.swift
    settings:
      base:
        INFOPLIST_FILE: GridPulseWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.gridpulse.widgets
        PRODUCT_NAME: GridPulseWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
