name: HabitWeave
options:
  bundleIdPrefix: com.example.habitweave
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  HabitWeave:
    type: application
    platform: iOS
    sources:
      - path: HabitWeave
    settings:
      base:
        INFOPLIST_FILE: HabitWeave/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.habitweave
        PRODUCT_NAME: HabitWeave
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: HabitWeaveWidgets
    entitlements:
      path: HabitWeave/HabitWeave.entitlements
      properties:
        com.apple.security.app-sandbox: true

  HabitWeaveWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: HabitWeaveWidgets
      - path: HabitWeave/Models/Habit.swift
      - path: HabitWeave/Models/HabitRecord.swift
    settings:
      base:
        INFOPLIST_FILE: HabitWeaveWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.habitweave.widgets
        PRODUCT_NAME: HabitWeaveWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
