name: InvisibleWall
options:
  bundleIdPrefix: com.example.invisiblewall
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  InvisibleWall:
    type: application
    platform: iOS
    sources:
      - path: InvisibleWall
    settings:
      base:
        INFOPLIST_FILE: InvisibleWall/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.invisiblewall
        PRODUCT_NAME: InvisibleWall
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: InvisibleWallWidgets
    entitlements:
      path: InvisibleWall/InvisibleWall.entitlements
      properties:
        com.apple.security.app-sandbox: true

  InvisibleWallWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: InvisibleWallWidgets
    settings:
      base:
        INFOPLIST_FILE: InvisibleWallWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.invisiblewall.widgets
        PRODUCT_NAME: InvisibleWallWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
