name: TypeGuard
options:
  bundleIdPrefix: com.example.typeguard
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  TypeGuard:
    type: application
    platform: iOS
    sources:
      - path: TypeGuard
    settings:
      base:
        INFOPLIST_FILE: TypeGuard/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.typeguard
        PRODUCT_NAME: TypeGuard
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: TypeGuardWidgets
    entitlements:
      path: TypeGuard/TypeGuard.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.developer.sensorkit.reader.allow: true

  TypeGuardWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: TypeGuardWidgets
      - path: TypeGuard/Models/TypingBiomarker.swift
      - path: TypeGuard/Models/BaselineProfile.swift
    settings:
      base:
        INFOPLIST_FILE: TypeGuardWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.typeguard.widgets
        PRODUCT_NAME: TypeGuardWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
