name: FoodLogAI
options:
  bundleIdPrefix: com.example.foodlogai
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  FoodLogAI:
    type: application
    platform: iOS
    sources:
      - path: FoodLogAI
    settings:
      base:
        INFOPLIST_FILE: FoodLogAI/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.foodlogai
        PRODUCT_NAME: FoodLogAI
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: FoodLogAIWidgets
    entitlements:
      path: FoodLogAI/FoodLogAI.entitlements
      properties:
        com.apple.security.app-sandbox: true

  FoodLogAIWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: FoodLogAIWidgets
      - path: FoodLogAI/Models/Meal.swift
      - path: FoodLogAI/Models/Dish.swift
      - path: FoodLogAI/Models/DailyNutrition.swift
    settings:
      base:
        INFOPLIST_FILE: FoodLogAIWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.foodlogai.widgets
        PRODUCT_NAME: FoodLogAIWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
