name: TimeMap
options:
  bundleIdPrefix: com.example.timemap
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  TimeMap:
    type: application
    platform: iOS
    sources:
      - path: TimeMap
    settings:
      base:
        INFOPLIST_FILE: TimeMap/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.timemap
        PRODUCT_NAME: TimeMap
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: TimeMapWidgets
    entitlements:
      path: TimeMap/TimeMap.entitlements
      properties:
        com.apple.security.app-sandbox: true

  TimeMapWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: TimeMapWidgets
      - path: TimeMap/Models/ScheduleEvent.swift
      - path: TimeMap/Models/TimeSlot.swift
    settings:
      base:
        INFOPLIST_FILE: TimeMapWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.timemap.widgets
        PRODUCT_NAME: TimeMapWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
