name: LiveBoard
options:
  bundleIdPrefix: com.example.liveboard
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  LiveBoard:
    type: application
    platform: iOS
    sources:
      - path: LiveBoard
    settings:
      base:
        INFOPLIST_FILE: LiveBoard/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.liveboard
        PRODUCT_NAME: LiveBoard
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: LiveBoardWidgets
    entitlements:
      path: LiveBoard/LiveBoard.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.com.example.liveboard

  LiveBoardWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: LiveBoardWidgets
      - path: LiveBoard/Models/TeamMember.swift
      - path: LiveBoard/Models/BoardTask.swift
      - path: LiveBoard/Models/TeamBoard.swift
    settings:
      base:
        INFOPLIST_FILE: LiveBoardWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.liveboard.widgets
        PRODUCT_NAME: LiveBoardWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
    entitlements:
      path: LiveBoard/LiveBoard.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.com.example.liveboard
