name: VoiceStudio
options:
  bundleIdPrefix: com.example.voicestudio
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  VoiceStudio:
    type: application
    platform: iOS
    sources:
      - path: VoiceStudio
    settings:
      base:
        INFOPLIST_FILE: VoiceStudio/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.voicestudio
        PRODUCT_NAME: VoiceStudio
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    entitlements:
      path: VoiceStudio/VoiceStudio.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true
