name: GreenCharge
options:
  bundleIdPrefix: com.example.greencharge
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  GreenCharge:
    type: application
    platform: iOS
    sources:
      - path: GreenCharge
    settings:
      base:
        INFOPLIST_FILE: GreenCharge/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.greencharge
        PRODUCT_NAME: GreenCharge
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: GreenChargeWidgets
    entitlements:
      path: GreenCharge/GreenCharge.entitlements
      properties:
        com.apple.security.app-sandbox: true

  GreenChargeWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: GreenChargeWidgets
      - path: GreenCharge/Models/GridForecast.swift
      - path: GreenCharge/Models/ChargingSession.swift
      - path: GreenCharge/Models/GreenScore.swift
    settings:
      base:
        INFOPLIST_FILE: GreenChargeWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.greencharge.widgets
        PRODUCT_NAME: GreenChargeWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
