name: SocialPulse
options:
  bundleIdPrefix: com.example.socialpulse
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  SocialPulse:
    type: application
    platform: iOS
    sources:
      - path: SocialPulse
    settings:
      base:
        INFOPLIST_FILE: SocialPulse/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.socialpulse
        PRODUCT_NAME: SocialPulse
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: SocialPulseWidgets
    entitlements:
      path: SocialPulse/SocialPulse.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.developer.sensorkit.reader.allow: true

  SocialPulseWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: SocialPulseWidgets
      - path: SocialPulse/Models/SocialScore.swift
      - path: SocialPulse/Models/CommunicationRecord.swift
      - path: SocialPulse/Models/VisitRecord.swift
      - path: SocialPulse/Models/WeeklyReport.swift
    settings:
      base:
        INFOPLIST_FILE: SocialPulseWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.socialpulse.widgets
        PRODUCT_NAME: SocialPulseWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
