name: MeetingLens
options:
  bundleIdPrefix: com.example.meetinglens
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  MeetingLens:
    type: application
    platform: iOS
    sources:
      - path: MeetingLens
    settings:
      base:
        INFOPLIST_FILE: MeetingLens/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.meetinglens
        PRODUCT_NAME: MeetingLens
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: MeetingLensWidgets
    entitlements:
      path: MeetingLens/MeetingLens.entitlements
      properties:
        com.apple.security.app-sandbox: true

  MeetingLensWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: MeetingLensWidgets
      - path: MeetingLens/Models/MeetingEvent.swift
      - path: MeetingLens/Models/MeetingStats.swift
    settings:
      base:
        INFOPLIST_FILE: MeetingLensWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.meetinglens.widgets
        PRODUCT_NAME: MeetingLensWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
