name: SynthLab
options:
  bundleIdPrefix: com.example.synthlab
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  SynthLab:
    type: application
    platform: iOS
    sources:
      - path: SynthLab
    settings:
      base:
        INFOPLIST_FILE: SynthLab/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.synthlab
        PRODUCT_NAME: SynthLab
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: SynthLabWidgets
    entitlements:
      path: SynthLab/SynthLab.entitlements
      properties:
        com.apple.security.app-sandbox: true

  SynthLabWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: SynthLabWidgets
    settings:
      base:
        INFOPLIST_FILE: SynthLabWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.synthlab.widgets
        PRODUCT_NAME: SynthLabWidgets
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
