name: ARTimeTraveler
options:
  bundleIdPrefix: com.example.artimetraveler
  deploymentTarget:
    iOS: "18.0"
settings:
  base:
    SWIFT_VERSION: "6.1"
    SWIFT_STRICT_CONCURRENCY: complete
targets:
  ARTimeTraveler:
    type: application
    platform: iOS
    sources:
      - ARTimeTraveler
    settings:
      base:
        INFOPLIST_FILE: ARTimeTraveler/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.artimetraveler
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
